package Interfaces.IHMHome;

import javax.swing.*;
import java.awt.*;

/**
 * Created by marouanebenalla on 31/10/2016.
 */
public class Loading extends JFrame {
    private JPanel panel1;
    private JTextPane thisSoftwareHasBeenTextPane;
    private JTextPane allTheRightsAreTextPane;
    private JTextPane authorsMarouaneBENALLAJeanTextPane;
    private JProgressBar progressBar1;

    private void createUIComponents() {
        // TODO: place custom component creation code here
        panel1 = new JPanel();
    }

    public static void main(String[] args) {
        try {
            Loading frame = new Loading();
            Thread.sleep(2000);
            frame.setValue(10);
            Thread.sleep(2000);
            frame.setValue(20);
            Thread.sleep(2000);
            frame.setValue(70);
        } catch (InterruptedException e) {

        }

    }

    public Loading() {
        $$$setupUI$$$();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setContentPane(panel1);
        setUndecorated(true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        setSize(new Dimension(500, 600));
        setLocationRelativeTo(null);
        setVisible(true);


    }

    public void setValue(int progress) {
        progressBar1.setValue(progress);
        revalidate();
        repaint();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-3737345));
        panel1.setEnabled(true);
        thisSoftwareHasBeenTextPane = new JTextPane();
        thisSoftwareHasBeenTextPane.setBackground(new Color(-3933953));
        thisSoftwareHasBeenTextPane.setEditable(false);
        thisSoftwareHasBeenTextPane.setEnabled(false);
        thisSoftwareHasBeenTextPane.setFont(new Font("Ayuthaya", Font.PLAIN, 10));
        thisSoftwareHasBeenTextPane.setForeground(new Color(-12040120));
        thisSoftwareHasBeenTextPane.setText("This software has been developed under MIT Licence, so you have the right to update it, change it or remove any thing you find useless but don't forget the persons who speends hours in developing it.\n\n");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(thisSoftwareHasBeenTextPane, gbc);
        allTheRightsAreTextPane = new JTextPane();
        allTheRightsAreTextPane.setBackground(new Color(-3933953));
        allTheRightsAreTextPane.setEditable(false);
        allTheRightsAreTextPane.setEnabled(false);
        allTheRightsAreTextPane.setFont(new Font("Ayuthaya", Font.PLAIN, 10));
        allTheRightsAreTextPane.setText("All the rights are reserved. CentraleSupelec 2016. SIS. ");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(allTheRightsAreTextPane, gbc);
        authorsMarouaneBENALLAJeanTextPane = new JTextPane();
        authorsMarouaneBENALLAJeanTextPane.setBackground(new Color(-3999746));
        authorsMarouaneBENALLAJeanTextPane.setEditable(false);
        authorsMarouaneBENALLAJeanTextPane.setEnabled(true);
        authorsMarouaneBENALLAJeanTextPane.setForeground(new Color(-16645630));
        authorsMarouaneBENALLAJeanTextPane.setText("Authors: Marouane BENALLA, Jean-loup VIARD\n");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(authorsMarouaneBENALLAJeanTextPane, gbc);
        final JToolBar.Separator toolBar$Separator1 = new JToolBar.Separator();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(toolBar$Separator1, gbc);
        final JLabel label1 = new JLabel();
        label1.setAlignmentX(0.0f);
        label1.setAlignmentY(0.0f);
        label1.setBackground(new Color(-8616823));
        label1.setEnabled(true);
        label1.setFocusCycleRoot(true);
        label1.setFont(new Font("Arial", Font.PLAIN, 48));
        label1.setForeground(new Color(-14775861));
        label1.setHorizontalAlignment(4);
        label1.setInheritsPopupMenu(true);
        label1.setText("Home Kit Interface");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        panel1.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setBackground(new Color(-983553));
        label2.setIcon(new ImageIcon(getClass().getResource("/icons/SEO-Connected-pic.png")));
        label2.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        panel1.add(label2, gbc);
        progressBar1 = new JProgressBar();
        progressBar1.setValue(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(progressBar1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
